import type { Metadata } from "next";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config/wallet";
import Web3ModalProvider from "@/contexts/wagmi";
import "@/styles/globals.css";
import { poppins } from "./fonts";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Fortune | PolarFi",
  description: "Generated by create next app",
  openGraph: {
    title: "Fortune",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Fortune",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={poppins.className}>
        <Web3ModalProvider initialState={initialState}>
          {children}
        </Web3ModalProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
